### ISSUE TITLE
Better testability for flux-angular

### ISSUE THREAD

**Issue by SuperheroicCoding** [christianalfoni/flux-angular#12]
Following scenario:

We have a big app with a modular sourcecode organisation. 
Each submodule is responsible for a definitive concern. 
These modules keep track of there state within there own stores.

E.g. 
* myApp 
  * login -> LoginStore
  * registration -> RegistrationStore

When it comes to unit testing, I want to test my units isolated from other units.
Now the problem when trying to test my LoginStore isolated with following code: 
```javascript
describe('LoginStore', function () {
    var loginStore;
    beforeEach(module('myApp.login'));
    beforeEach(inject(function (LoginStore) {
        loginStore = LoginStore;
    }));

    it('should be defined', function () {
        expect(loginStore).toBeDefined();
      }
    );
  });

````
...Is that the RegistrationStore (and all other stores) must also be available, because all js files are loaded into test suit and the angular.store method is invoked (I guess) on bootstrap. This method saves the stores in some contexts and later when injecting the LoginStore, the RegistrationModule is not available and therefore the RegistrationStore is not found, what leads to an `UnknownProvider` error: 
`Error: [$injector:unpr] Unknown provider: RegistrationStoreProvider <- RegistrationStore`.

I could fix my unit test by loading the module for registration before each test, but this leads to a chain of more dependencies, that I actually don't want to test and configure in this scenario.

Can you maybe change this behavior and only register the stores when they are actually created? 
I think it's something about the preinjection and the storeNames array. 
```javascript
moduleInstance.store = function (storeName, storeDefinition) { // Line 82 flux.angular-2.0.1
  ...
  this.factory(storeName, ['$injector', 'flux', function ($injector, flux) {
    ... invoked later ...
  }; 

  // Add store names for pre-injection 
  storeNames.push(storeName);
  return this;
};
```
Thank you for diving deeper! I will also try to solve it.

**Comment by christianalfoni** [comment]
Hi again and thanks for taking the time to find a solution for this :-)

When developing the new version I hit a scenario where you would use the **waitFor** method to wait for a store that was not instantiated yet. I did not consider a test scenario where you would not want this to happen. 

What do you think about using the same "angular.mock" check to use the pre-injection or not?

**Comment by SuperheroicCoding** [comment]
Wow fastest reply ever!!! Thanks a lot, that is great!

I think using the mock check is not the root cause of the problem. 
Do you really need this global variables and the pre-injection? 
Maybe there is an angulary way that utilizes dependency injection to solve this problem...
What do you think about raising the test coverage of your fancy fluxy module?

**Comment by christianalfoni** [comment]
Hehe, good timing, thats all ;-)

The lib is built with browserify so it is wrapped in an IIFE, so they are not as global as they seem ;-)

The pre-injection is there to prevent weird scenarios where you depend on the stores with the Yahoo Dispatchr, but angular has not loaded them yet. It gets very confusing when it happens, though it is an edge case. But I think it would be good to find a solution where that is kept. 

But okay, just to repeat the theory. When the unit tests runs it loads all angular files, causing the "store names" array to be filled up. When you use `module("myApp.login")` it will try to invoke all the the stores in the names array, but since you just loaded only a specific module a lot of the stores are not available for invocation.

I really do think your problem is fixed by not doing this invoking during testing because then it relies on "register store on injection", which is what you want? 

Of course have to test it :-) Does it seem like I understand the issue?

Testing would of course be great and as we have a couple of bugs here now it seems like a good idea to set it up :-) Will find some time to do it asap.

**Comment by SuperheroicCoding** [comment]
Hi again,

yes, you understood the scenario and yes my problem would be solved by checking if mock is available, but to me it still feels like a hack.

We should consider to adapt the waitFor method. I will also take a look into it.

**Comment by christianalfoni** [comment]
Actually, initially the **waitFor** referenced the instance of a store, instead of the name. But that causes circular dependency problems if you have some handler the waits for a store where a different handler waits for the same store again.

It is a tough one ;-)

But flux-angular already checks for angular.mock for store-resets during unit testing. It could just use the same check for pre-injection. I do see your point with it being a hack, I had to think about it a bit. My conclusion was that flux-angular should know what mode Angular is running in to optimize its testability. Just like Angular has angular.mock to optimize its testability. The best solution I found  was to check for "angular.mock" :-)

Just to make sure there was no misunderstanding with usage of "angular.mock". I did not want you to put that in your code-base, want it to be part of flux-angular to make it easier to test.

**Comment by SuperheroicCoding** [comment]
Ok, thanks a lot for your effort and of cause it will  solve the problem. 

It's a good way to ask for angular.mock and try to optimize behavior while testing. 
So don't get me wrong. I like your work, maybe my background as java developer makes me too critical, so sorry for that. My hacky feeling comes mostly from injecting all stores in the rootscope on bootstrap and the 'almost globals'. 
I would try to eliminate that asap. E.g. by using a service like a registry for the stores that holds the global necessary information... thinking about it it seems like a good job for a store... but which came first? the chicken or the egg? ;)

Are you going to implement the check for angular.mock for the rootscope?

Thanks and have fun!

**Comment by christianalfoni** [comment]
Hehe, no worries, I like that you challenge the ideas and implementations. It is a great way for me to learn and think about how and why I do things the way I do ;-)

Maybe the concept of closures makes things feel a bit hacky, coming from other languages, but actually a closure around some code is how modules are created in JavaScript. So:

```javascript
// requirejs
define(['myDep1'], function () {
  return {};
});
// browserify
var require('myDep1');

module.exports = {};
// IIFE
var exports = (function () {

}(myDep1));
```
These are all pretty much the same thing, as they end up as the IIFE example when bundled together (requirejs, browserify, webpack etc.). Coming from Java I can see that it feels weird, and I can see why angular.module() feels more modular, but it really isn't. It will of course be good to get actual javascript modules in ES6, though they will probably also be bundled the same way as requirejs, browserify etc. until HTTP/2 comes a long.

Actually the $rootScope is untouched by flux-angular. The only thing happening in "run" is:

1. An empty function is run with the stores as dependencies. This forces the creation of the instances to make them ready to communicate with each other, even though your app for some reason did not specifically inject them

2. The delegated methods for angular scopes ($on, $off, $apply etc.) are extended with a new method, $listenTo. By using the closure of flux-angular we access a private list of stores

When writing this and thinking about it I totally understand that you feel like it is hacky, but closures are one of the most powerful features of JavaScript. Think of flux-angular like this:

```javascript
(function (angular) {
  // > flux-angular module scope with access to angular
    // > flux-angular specifics
       // > angular specifics
}(angular));
```

So there is absolutely no globals here at all. The flux-angular module wraps its implementation details around an angular module. JavaScript closures makes it possible for the Angular implementation to access anything in the flux-angular module scope, but nothing can reach flux-angular from the outside. Using a service would make it possible for a developer to access flux-angular implementation specifics, which kinda breaks the purpose :-)

Sorry if I explained details obvious to you, but it was as much for my own sake :-)

**Comment by SuperheroicCoding** [comment]
Thanks for the nice explanations. I really like the idea behind closures and functional code. 
One principle of functional programming is, that you should avoid variables that hold state wherever possible to reduce side effects. And there comes this hacky feeling from. 
You manipulate a variable in one method, that changes behavior inside another method. 
I think you can do better... :). In your method this variable is not injected. It's just there from outer context. 
If you pull out your method into another context, it's not working anymore. 
Therefore testability and stability is bad. Because you have to create a global context before you can test the methods.

I still think it's better to inject a service that manipulates the state of the storeNames, storeExports and stores. Also for testing it might be good to expose even the inner structure of the stores... 

If you try to write unit tests for your specific methods and you getting confused how to create the context for one method or object to test, you see that there are to much implicit dependencies. So for me TDD is a great way to build up experience about how to make a component/method/object testable and minimize side-effects. 

:)

**Comment by SuperheroicCoding** [comment]
Anyway I am totally happy with your module and your solution for testing module stores. 
We want to use your solution for a productive system and for our quality demands we would be even happier if you find your time and reach a better test coverage...

**Comment by christianalfoni** [comment]
Hi again @SuperheroicCoding :-)

Hehe, my code is definitely not functional :-) How do you solve the "hide implementation details vs testability"? Do you mostly make everything open and it is more of a discipline to not touch certain parts and/or ignore properties (typically _myPropName)? I built this module loader, [module-loader-tdd](https://github.com/MarcelloSystems/module-loader-tdd) which gives a private object to hide implementation details on. During testing you have access to that private object. Kinda cool, but yeah, this is a difficult balance.

As an exercise I am going to put the implementation details into a service, to make it easier to test also. Then I will write some tests for flux-angular :-) Will also add the mock check so that angular tests works as expected. The flux.createStore method is a good idea, will bring that into the scope of next release.

Thanks for taking the time to discuss these details, it will certainly make flux-angular more robust :-)

**Comment by SuperheroicCoding** [comment]
Good morning, yes that's an old problem and there is no easy solution. It depends... For unit tests I want to test the implementation details. And therefore the _ convention is for my purposes good enough. 
For integration test it's more about testing the interface. 
I think I have to extract the store definitions into a service and then unit test it. 

Interesting module-loader. Thanks for the hint. I will take a lock at it. 

In the case of testing stores it was quite an surprise that the details were not available anymore. But after thinking about it, it makes sense to hide the inner properties... I mean it's a flux store... :) 

After using your version 2 for a while, in my opinion the brave monkeypatch is a little bit to much . A store is such a specific thing, that it's more than a service or factory in an angular context. 
It depends on external libraries and makes fancy thinks with my store definition... 
For me, the flux module with service methods felt better. There is no big difference for the code when I say 
`angular.module.factory(function(flux){return flux.createStore({myStoreDefinition})})` or
`angular.module.store(function(){return {myStoreDefinition}})`.
What do you think about it it? 

I am not sure, did you write Angular2 will support Flux Architecture? If so do you have a link or paper? 

Hopefully my opinions are helping to create nice discussions and not to upset you! :) 

Looking forward for your next version!

**Comment by christianalfoni** [comment]
Hi,

You give great feedback so do not worry about upsetting me, though I do appreciate that you are nice about it :-) 

flux.createStore is coming back in next version.

When it comes to Flux Architecture there are lots of different implementations, and reads. The core idea is to have a "one way flow" of state and you also get a clear separation of your application state and view/component state. I actually have a video on this subject you might find interesting... did I share it before? Anyways, here it is: [Going from MVC to Flux](https://www.youtube.com/watch?v=plUN2L4Ak14). 

So flux-angular honors the one way flow of state and has a strong concept of where to put the state of your application. Then you have the building blocks. Actions, action creators, stores, dispatchers, components etc. I think the community is still trying to figure out exactly how to implement the concepts of flux, but the idea itself has set root :-) In flux-angular you pretty much have a dispatcher that points directly to your stores.

Here are some resources, [react js wiki](https://github.com/facebook/react/wiki/Complementary-Tools)

**Comment by christianalfoni** [comment]
Okay, got a new version out with testing. Thanks for the discussions! :-)

**Comment by SuperheroicCoding** [comment]
Great new version. Thanks a lot for your work!

**Comment by christianalfoni** [comment]
Thanks for the feedback :-) Let me know if you have more ideas or scenarios that needs to be solved!
