### ISSUE TITLE
Does immutable reduce rendering?

### ISSUE THREAD

**Issue by jrust** [christianalfoni/flux-angular#34]
I'm trying to figure out the benefits of using immutability store vs deep cloning.  My initial thought was that it would reduce the number of times Angular had to render the DOM in an ng-repeat (if used in conjunction with `track by`).  However, so far my testing isn't bearing this out -- the ng-repeat seems to be kicked off every time a change causes the listenTo callback to be fired and re-sync the data (and along similar lines, the $scope.$watch on the same property is also invoked the same number of times).  I'm wondering if this is because of the fact that even with immutability I still have to call `toJS()` on the data before handing it over to Angular.  Will `toJS()` end up giving a new object reference every time?

Aside from the ng-repeat, are there other pros and cons of immutability mode? I'm happy to try and take anything learned here and add it to the README

**Comment by christianalfoni** [comment]
Hi @jrust :-)

I should be a bit careful about how a state this advantage. The most important benefit, compared to previous version of flux-angular is the cloning part. Instead of the store always cloning what you grab with the exports, it will just return whatever is in the store.

You should think of toJS() as a copy of the data structure. It makes it easier for you to do mutations... you should not use that with ng-repeat for example.

But you gave me an idea with this issue. I could make immutable-store add an ID ($$hash) to all objects by default. That way you would never have to use "track by" and the rendering would indeed improve a lot as Angular does not have to create this hash. I will check this out.

Angular will never get the full benefit of immutability I think, as it is not designed for it. But I am trying to take it as far as possible :-)

**Comment by christianalfoni** [comment]
Okay, so I have created a jsPerf

http://jsperf.com/immutable-store-in-angular

This test simulates the cloning of normal flux-angular, by changing out the array being used in the ng-repeat. New array and objects each time, as cloning would do. Then it runs it against the immutable store where it is the same array and objects each time. Immutable store runs around 80% faster.

The $$hashKey thingy was not a good idea :-) Better to keep with current Angular optimizations, like track by $index and track by item.id, than turning it around. It did not give any perf gains either really.

Is your test similar to the js perf test?

**Comment by jrust** [comment]
Thanks for taking a look into this @christianalfoni.  So, I put together a plunker to play with it a bit: http://plnkr.co/edit/MeWQva7lVwZAJsWxDHJO

Here's what I've learned from your experiments and mine:
 
Downsides of immutable: 
* slower writes
* more cumbersome API for making changes
* need to always use track by for ng-repeat or else it will give a $$hashKey error (is there anywhere else where Angular tries to modify a variable that would cause failure like this?)

Upsides of immutable:
* Faster reads because no deep clone
* Less renders and scope.$watch triggers (in the plunker you can see that successive clicks on the "set immutable" don't increase the render count)
* Works without needing toJS() for primitives (e.g. somehow the ng-model binding worked even without toJS)
* if you can't use track by then you can use toJS(), but it gives a new copy each time which loses the benefit of less renders.

Does that sound about right?  Anything I missed?

**Comment by christianalfoni** [comment]
Hi @jrust ,

Jup, you are exactly right!

I do not think Angular interferes with $$hashKey anywhere.

primitives copies when referencing, so that works.

```js
// Lets say MyStore.foo = 'bar';

// This one can be ng-modeled
$scope.foo = MyStore.foo;

// MyStore.foo = { foo: 'bar' }

// foo.foo can not be ng-modeled
$scope.foo = MyStore.foo;

```

I can not see a situation where you are unable to use "track by"? Even Angular team recommends it? Either `track by $index` or a prop on each object. But yeah, you are correct :-)

Nice work, tracking this stuff, thanks a lot!
