### ISSUE TITLE
immutable-store deprecated, other options?

### ISSUE THREAD

**Issue by ddho23** [christianalfoni/flux-angular#51]
Now that immutable-store has been deprecated, should we use a different library for immutable mode?

**Comment by christianalfoni** [comment]
Hi @ddho23, 

Initially I wanted to use Baobab, but it was missing immutability. But now it has it so the project should switch to that, which it will in next version

**Comment by christianalfoni** [comment]
Please give me your thoughts on this, as this is just my current perspective :)

**Comment by jrust** [comment]
After coming across [a significant issue](https://github.com/christianalfoni/immutable-store/issues/19) in immutable-store I've decided to work on replacing immutable-store with [freezer](https://github.com/arqex/freezer).  I looked at several different immutable stores including baobab, immutable-js, and seamless-immutable, but only freezer has the performance and ability to treat the store as native JS types that immutable-store has. 

So, my current plan is to create a PR that swaps out immutable-store with freezer.  This will unfortunately require breaking changes because freezer returns the cursor when you mutate instead of returning the new store (so `state = state.set('a', 1)` becomes `state.get().set('a', 1)`)  However, freezer also has a listener API which means we could get rid of the need for `emitChange()` when in immutable mode!

As to thoughts on the future, I think projects like cerebral (and others that utilize the single-store idea, like redux) are very promising. However, I also know we have a large app on flux-angular and it would be a significant upgrade to switch to them.  Additionally, the "traditional" flux model is tested, reliable, and easily portable to angular 2.  All of which is to say I see many reasons to keep this project alive and moving forward.

Thoughts or questions welcome!

**Comment by christianalfoni** [comment]
I think this looks great @jrust and really glad if you want to make a pull request on this. Maybe you could do that and I can review? And when I merge it in I can make you official collaborator in case any issues would arise later?

**Comment by jrust** [comment]
Sounds good.  We've got it scheduled for this sprint so hopefully in the next week or two!

**Comment by jrust** [comment]
@christianalfoni I got a branch made that uses freezer, and then I came across [an issue](https://github.com/arqex/freezer/issues/3) you had created there that led to immutable-store.  And the point made in that issue about freezer allowing code outside the store to mutate the store seems very valid.  The only option I can come up with for preventing that is re-enabling deep cloning of all the export methods.  This could be done only in development, which perhaps isn't too bad (other projects like baobab and seamless-immutable also recommend turning off immutability in production).  I did see that baobab seems to take the same paradigm as freezer in that you don't have to re-assign the changes back to a variable.  So have your thoughts on this changed or do you see any other solutions? Thanks!

**Comment by jrust** [comment]
After looking at how cerebral is doing it I'm now starting to be inclined towards baobab because it has the event emitting, forces immutability when you use `.get()` and because `get()` gives back an object/array that still works really nicely with lodash.  The downside is the need to use the cursor form of getting access to the property instead of the dot notation that freezer and immutable-store enabled, but I'm thinking that may be worth it since only the stores have to worry about that.  Open to thoughts or suggestions, though!

**Comment by christianalfoni** [comment]
Hi @jrust ,

Baobab is really great piece of technology and I have only good things to say about it. I did look into freezer, which is also great, but Baobab gives you a different approach too. You can use cursors to listen for changes at specific points in the tree, instead of having a general change event and do shallow checking to see if any state has changed. If you look at baoab-react, you can see how it is implemented there. That is actually the most optimal way of handling state changes. 

Let me know if you have any questions related to this. I will gladly help :-)
