### ISSUE TITLE
$listenTo a store in a nested directive that have an isolate scope

### ISSUE THREAD

**Issue by pribilinskiy** [christianalfoni/flux-angular#55]
Giving an example where `MyStore` is immutable:

```
	app.directive('myDirective', function() {
		return {
			replace: true,
			transclude: true,
			scope: {
				config: '=',
			},
			controller: function($scope, MyStore) {

				$scope.$listenTo(MyStore, function() {
					console.log($scope.config.value);
				});
			},
			template: '{{config.value}}'
		}
	});
```

When the `*` event occurs, the `$scope.config` which is a descendant object of MyStore, part of `ng-repeat` loop, still references to an object of **previous state** in `$listenTo` callback.

Yet the template does have access to the **updated** `config.value`

That forced me to provide the `index` to the isolate scope and access `MyStore` in the `$listenTo` callback, thus the `myDirective` now have to know the `full.path.to.the.config` object :(

Oh my, just got an `EventEmitter memory leak detected.` error. Replaced `listenTo` with `$broadcast` / `$on`

Is there a better solution to work around that issue? 

`$scope.$watch` can't be used for obvious reasons

**Comment by christianalfoni** [comment]
Hm, just repeating to see if I understand this correctly.

You have a directive that receives the config object from the immutable store? When whatever uses that directive updates, the passed config object does not update in the directive?

**Comment by pribilinskiy** [comment]
@christianalfoni exactly, and some of the deep values from `$scope.config` are required in e.g. `ng-model`.

I understand that the isolate scope is still bound to old instance of 'some.object.from.parent.scope' and `$listenTo` cannot be used in a directive that is part of `ng-repeat` because of `EventEmitter` limitations.

Solution to this problem may look quite complicated. 
In the directive that is part of `ng-repeat` I listen for an event:
```
$scope.$on('MyStoreUpdated', function update() { 
    $scope.someArray[index] = config.someArray[index]; 
});
``` 
The `config` service emits the `MyStoreUpdated` after getting required data from the immutable store, it communicates with the store through actions and gets data from exports and then converts that data to regular object for `ng-model` with `toJS()`.

The system looks very verbose and I hope that with Cerberal being more thoughtful in managing states will lower the verbosity.

**Comment by christianalfoni** [comment]
Hi @pribilinskiy,

Yeah, flux-angular is based on the early implementation of Flux. Specifically the Yahoo version of flux. A lot has happened since then and Cerebral has taken all the goodness of immutability and a "single state store", a long with its own ability to express complex state changing flows.

Cerebral is starting to get a good foothold and I really hope to bring devs from flux-angular over to the new project as it is more mature in the sense of what flux has evolved to :-)

Hm, seems a bit weird that the old reference to config is kept as the parent will change it when store updates. Angular was never really built for immutability so we might have found a scenario where Angular comes a bit short. I would have to look more deeply into this, but as you have found a solution I will have to fix some more pressing issues first.

Let me know if you think this should be a priority :-)

**Comment by jrust** [comment]
Version 3.0 has lowered some of the verbosity and changed the emitter library which should help.  Additionally, you can now listen for changes on a specific index in an array if you want, see #59
