### ISSUE TITLE
Emit custom event from each store

### ISSUE THREAD

**Issue by creative-eye** [christianalfoni/flux-angular#59]
We could emit specific events on each store, instead of the standard this.emitChange(). This might be useful if we have multiple things updating at once, but are interested only in a specific change. What do you think?

**Comment by jrust** [comment]
This is fixed in 3.0.0 since you can now listen for changes on a specific leaf of your data tree. e.g.:
a store that has the following state:
```javascript
initialize: function() {
  this.state = this.immutable({ selectedColor: 'blue', colors: ['green', 'blue'] });
}
```

And in the controller:
```javascript
// Listen only for changes to selectedColor
$scope.$listenTo(colorStore, ['selectedColor'], yourCallback);
```

Alternatively, you could also look at the paths changed since that is passed to callbacks that listen to all changes on a store:
```javascript
$scope.$listenTo(colorStore, function(e) {
  if (_.includes(e.data.paths, ['selectedColor'])) {
    // selectedColor has changed
  }
});
```

See the [baobab docs](https://github.com/Yomguithereal/baobab) on events for more details.
